[build-system]
requires = [
	'meson>=1.4.0',
	'ninja>=1.8.2, !=1.13.0',
	'wheel',
	'f90wrap<=0.2.16', # 0.3.0 has the 'only' problem
	'oldest-supported-numpy; python_version=="3.8"',
	"numpy>=2.0.0; python_version>='3.9'",
	'setuptools>=61.0',
	#"meson-python>=0.13.0",
	#'f90wrap@git+https://github.com/jameskermode/f90wrap',
]
build-backend = 'setuptools.build_meta'

[project]
name = "qepy"
dynamic = ["version"]
license = { file = "License" }
description = "QEpy: Quantum ESPRESSO Python interface"
authors = [
	{name = "Michele Pavanello",  email = "m.pavanello@rutgers.edu"},
	{name = "Xuecheng Shao",      email = "shaoxc@jlu.edu.cn"},
]
maintainers = [
	{name = "Michele Pavanello",  email = "m.pavanello@rutgers.edu"},
	{name = "Xuecheng Shao",      email = "shaoxc@jlu.edu.cn"},
]
requires-python = ">=3.8"
dependencies = [
	'f90wrap<=0.2.16',
	"numpy>=1.19.3",
]
readme = "README.md"
classifiers = [
	'Development Status :: 3 - Alpha',
	'Intended Audience :: Science/Research',
	'Programming Language :: Python :: 3',
	'Programming Language :: Python :: 3.9',
	'Programming Language :: Python :: 3.10',
	'Programming Language :: Python :: 3.11',
	'Programming Language :: Python :: 3.12',
	'Programming Language :: Python :: 3.13',
	'Programming Language :: Python :: 3.14',
	'Topic :: Scientific/Engineering :: Chemistry',
    'Topic :: Scientific/Engineering :: Physics',
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]

[project.optional-dependencies]
docs = [
	"sphinx",
	"sphinx-rtd-theme>=2.0.0",
	"sphinx-panels",
	"sphinx-copybutton",
	"sphinx-inline-tabs",
	"nbsphinx",
	"pandoc"
]
test = [
	"pytest",
	"pytest-cov",
	"pytest-mpi",
	"ase"
]
all = [
	"mpi4py",
	"dftpy",
]

[project.urls]
homepage = "https://gitlab.com/shaoxc/qepy"
documentation = "http://qepy.rutgers.edu"
source = "https://gitlab.com/shaoxc/qepy"

[tool.setuptools.dynamic]
version = {attr = 'qepy.__version__'}

[tool.cibuildwheel]
before-build = "bash {project}/tools/wheels/cibw_before_build.sh {project}"

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"

[tool.cibuildwheel.linux.environment]
RUNNER_OS="Linux"
#PKG_CONFIG_PATH = "/project/.openblas"

[tool.cibuildwheel.macos]
#before-build = "bash {project}/tools/wheels/cibw_before_build.sh {project}"

[tool.cibuildwheel.macos.environment]
RUNNER_OS="macOS"
PKG_CONFIG_PATH = "{project}"
LIBMBD_C_API=0
