name: Build wheels

on:
  push:
    branches:
      - macos
    paths-ignore:
      - '.github/workflows/publish.yml'
  pull_request:
    branches:
      - macos

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.python }}-${{ matrix.buildplat[1] }}
      ${{ matrix.buildplat[2] }} ${{ matrix.buildplat[3] }}
      ${{ matrix.buildplat[4] }}
    runs-on: ${{ matrix.buildplat[0] }}
    strategy:
      fail-fast: false
      matrix:
        buildplat:
        - [ubuntu-22.04, manylinux, x86_64, "", ""]
        - [macos-15-intel, macosx, x86_64, openblas, "10.14" ]
        - [macos-14, macosx, arm64, openblas, "12.3"]
        python: ["cp38", "cp39", "cp312"]
        exclude:
        - buildplat: [macos-14, macosx, arm64, openblas, "12.3"]
          python: "cp38"
        #- buildplat: [macos-14, macosx, arm64, openblas, "12.3"]
        #  python: "cp39"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup OS & Compiler Environments
        env:
          TARGET_ARCH: ${{ matrix.buildplat[2] }}
          BLAS_VARIANT: ${{ matrix.buildplat[3] }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.buildplat[4] }}
        run: |
          source tools/wheels/arch_env.sh

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}*
          CIBW_ARCHS: ${{ matrix.buildplat[2] }}
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v7.0.0
        with:
          path: ./wheelhouse/*.whl
          name: ${{ matrix.python }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}-${{ matrix.buildplat[3] }}-${{ matrix.buildplat[4] }}
